os: linux

dist: trusty

before_install:
  - sudo apt-get update

addons:
  firefox: latest

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

#before_script:
#  - cd suites

jobs:
  include:
    - stage: test
      script: mvn test
#      script: mvn test -Dtest=JUnitSuiteTest
#      script: mvn clean install -f
