os: linux

dist: trusty

before_install:
  - sudo apt-get update

addons:
  firefox: latest

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: test
      script: mvn clean install
